spring:
  
  jpa:    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:      ddl-auto: create
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  data:    jpa:      repositories:        bootstrap-mode: default
  h2:    console:      enabled: true
   
server:  port: 8004